package ILLBEBACK;

// Copyright Wintriss Technical Schools 2013
import java.applet.AudioClip;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.URL;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JApplet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/* This recipe is to be used with the Jeopardy Handout: http://bit.ly/1bvnvd4 */

public class Jeopardy implements ActionListener {
	private JButton firstButton;
	private JButton secondButton;
	private JButton thirdButton, fourthButton, fifthButton;
	private JButton firstButton2, secondButton2, thirdButton2, fourthButton2, fifthButton2;
	private JPanel quizPanel;
	int score = 0;
	JLabel scoreBox = new JLabel("0");
	int buttonCount = 0;

	public static void main(String[] args) {
		new Jeopardy().start();
	}

	private void start() {
		JFrame frame = new JFrame();
		quizPanel = new JPanel();
		JPanel quizPanel2 = new JPanel();
		frame.setLayout(new BorderLayout());

		frame.add(quizPanel2);
		frame.setVisible(true);

		frame.setTitle("I am not in danger of losing my job");

		JPanel mrpanel = new JPanel();
		mrpanel = createHeader("Graphs");

		quizPanel.add(mrpanel);
		frame.add(quizPanel);
		JPanel panel = new JPanel();
		panel = createHeader("Guiness Book of World Records Record Holders");
		quizPanel.add(panel);

		firstButton = createButton("$200");
		firstButton.addActionListener(this);
		firstButton2 = createButton("$200");
		firstButton2.addActionListener(this);
		
		quizPanel.add(firstButton);
		quizPanel.add(firstButton2);

		secondButton = createButton("$400");
		secondButton.addActionListener(this);
		secondButton2 = createButton("$400");
		secondButton2.addActionListener(this);
		quizPanel.add(secondButton);
		quizPanel.add(secondButton2);

		quizPanel.setLayout(new GridLayout(6, 3));
		frame.add(makeScorePanel(), BorderLayout.NORTH);
		frame.setSize(Toolkit.getDefaultToolkit().getScreenSize().height,
				Toolkit.getDefaultToolkit().getScreenSize().width);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		thirdButton = createButton("$600");
		thirdButton.addActionListener(this);
		thirdButton2 = createButton("$600");
		thirdButton2.addActionListener(this);
		fourthButton = createButton("$800");
		fourthButton.addActionListener(this);
		fourthButton2 = createButton("$800");
		fourthButton2.addActionListener(this);
		fifthButton = createButton("$1000");
		fifthButton.addActionListener(this);
		fifthButton2 = createButton("$1000");
		fifthButton2.addActionListener(this);
		quizPanel.add(thirdButton);
		quizPanel.add(thirdButton2);
		quizPanel.add(fourthButton);
		quizPanel.add(fourthButton2);
		quizPanel.add(fifthButton);
		quizPanel.add(fifthButton2);

	}

	private JButton createButton(String dollarAmount) {

		JButton hello = new JButton();

		hello.setText(dollarAmount);

		buttonCount += 1;

		return new JButton(dollarAmount);
	}

	public void actionPerformed(ActionEvent arg0) {

		playJeopardyTheme();
		JButton buttonPressed = (JButton) arg0.getSource();

		if (buttonPressed == firstButton) {
			askQuestion("This graph is generated by the equation y = mx +b", "What is a line?", 200);
		}
		if (buttonPressed == firstButton2) {
			askQuestion("He was the fattest man in the world in 2014", "Who was Manuel Uribe?", 200);
		}
		if (buttonPressed == thirdButton) {
			askQuestion(
					"This triangle similarity is created by the length of all three sides of one triangle being multiples of all three sides of another triangle",
					"What is SSS similarity?", 600);
		}
		if (buttonPressed == thirdButton2) {
			askQuestion("This man lifted the largest weight ever in 1985, weighing 6270 pounds",
					"Who was Paul Anderson?", 600);
		}
		if (buttonPressed == fourthButton) {
			askQuestion("This graph's equation is quadratic", "What is a parabola?", 800);
		}
		if (buttonPressed == fourthButton2) {
			askQuestion("This person won the longest professional tennis match in all history, lasting 11 hours",
					"Who is John Isner?", 800);
		}
		if (buttonPressed == fifthButton) {
			askQuestion("This parametric equation generates a unit circle",
					"what is parametric equation x = cos t, y = sin t?", 1000);
		}
		if (buttonPressed == fifthButton2) {
			askQuestion("He owns the world record for the longest video game session ever played", "Who is Okan Kaya?",
					1000);
		}
		if (buttonPressed == secondButton) {
			askQuestion("The formula for this triangle's line lengths is: C^2 = A^2 + B^2","What is the pythagorean theorem?", 400);
		}
		if (buttonPressed == secondButton2) {
			askQuestion("She was the oldest cat ever to live.", "Who was Creme Puff?", 400);
		}

		buttonPressed.setText("");
	}

	private void askQuestion(String question, String correctAnswer, int prizeMoney) {

		String yello = JOptionPane.showInputDialog(question);

		if (yello.equalsIgnoreCase(correctAnswer)) {
			score += prizeMoney;
			updateScore();
			JOptionPane.showMessageDialog(null, "U IS RIGHT!");
		}

		else {
			score -= prizeMoney;
			JOptionPane.showMessageDialog(null, "Sorry, that is not right!, the correct answer is: " + correctAnswer);
			updateScore();
		}

	}

	public void playJeopardyTheme() {
		try {
			AudioInputStream audioInputStream = AudioSystem
					.getAudioInputStream(new File("/Users/League/Google Drive/league-sounds/jeopardy.wav"));
			Clip clip = AudioSystem.getClip();
			clip.open(audioInputStream);
			clip.start();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	private void playSound(String fileName) {
		AudioClip scream = JApplet.newAudioClip(getClass().getResource(fileName));
		scream.play();
	}

	private Component makeScorePanel() {
		JPanel panel = new JPanel();
		panel.add(new JLabel("score:"));
		panel.add(scoreBox);
		panel.setBackground(Color.CYAN);
		return panel;
	}

	private void updateScore() {
		scoreBox.setText("" + score);
	}

	private JPanel createHeader(String topicName) {
		JPanel panelj = new JPanel();
		panelj.setLayout(new BoxLayout(panelj, BoxLayout.PAGE_AXIS));
		JLabel l1 = new JLabel(topicName);
		l1.setAlignmentX(Component.CENTER_ALIGNMENT);
		panelj.add(l1);
		return panelj;
	}

	void showCorrectImage() {
		showImage("correct.jpg");
	}

	void showIncorrectImage() {
		showImage("incorrect.jpg");
	}

	private void showImage(String fileName) {
		JFrame frame = new JFrame();
		URL imageURL = getClass().getResource(fileName);
		Icon icon = new ImageIcon(imageURL);
		JLabel image = new JLabel(icon);
		frame.add(image);
		frame.setVisible(true);
		frame.pack();
	}
}
